const model = {
	app: {
		page: "overview",
	},

	inputs: {
		overview: {
			activeFilter: "all",
			prioritySortDirection: "descending",
		},
		search: {
			searchTerm: "",
		},
		addError: {
			title: "",
			description: "",
			severity: "",
			priority: "",
			personId: null,
		},
	},

	data: {
		persons: [
			{ id: 1, name: "Per" },
			{ id: 2, name: "Pål" },
			{ id: 3, name: "Espen" },
		],
		latestErrorId: 2,
		errors: [
			{
				id: 1,
				title: "Små avstandsendringer",
				description: "Margin mellom kort varierer litt mellom sider",
				severity: "low",
				priority: "low",
				status: "open",
				personId: 3,
			},
			{
				id: 2,
				title: "Login bug",
				description: "Error når du sender inn pålogging skjema",
				severity: "high",
				priority: "high",
				status: "open",
				personId: 1,
			},
			{
				id: 3,
				title: "Tekst overlapper i footer",
				description: "Footer-tekst får liten overlap på små skjermer",
				severity: "low",
				priority: "low",
				status: "open",
				personId: null,
			},
			{
				id: 4,
				title: "Knapp virker ikke",
				description: "Submit-knappen responderer ikke ved klikk",
				severity: "medium",
				priority: "high",
				status: "open",
				personId: 3,
			},
			{
				id: 5,
				title: "Tekst casing inkonsistent",
				description: "Noen overskrifter er i Title Case, andre ikke",
				severity: "low",
				priority: "low",
				status: "open",
				personId: 2,
			},
			{
				id: 6,
				title: "API feiler",
				description: "Henter ikke data fra backend",
				severity: "high",
				priority: "high",
				status: "open",
				personId: null,
			},
			{
				id: 7,
				title: "Ikon litt forskjøvet",
				description: "Profilikon er 2px ute av posisjon i Chrome",
				severity: "low",
				priority: "low",
				status: "open",
				personId: 1,
			},
			{
				id: 8,
				title: "Layout på mobilen",
				description: "Layout funker ikke på mobilen",
				severity: "low",
				priority: "medium",
				status: "closed",
				personId: 2,
			},
			{
				id: 9,
				title: "Feil validering",
				description: "Skjema godtar ugyldig e-postadresse",
				severity: "medium",
				priority: "medium",
				status: "open",
				personId: 2,
			},
			{
				id: 10,
				title: "Hover-effekt treg",
				description: "Knapp hover-animasjon er litt treg i Safari",
				severity: "low",
				priority: "low",
				status: "closed",
				personId: null,
			},
		],
	},
};
